version: 0.2

phases:

  install:
    commands:
      - cd /usr/bin
      - pip3 install checkov

  build:
    commands:   
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -no-color
      - terraform init
      - terraform plan --out tfplan.binary
      - terraform show -json tfplan.binary > tfplan.json
      - checkov -f tfplan.json

  post_build:
    commands:
      - echo "Checkov test is completed on `date`"
