version: 0.2

env:
  variables:
    TF_VERSION: "1.0.6"

phases:

  install:
    commands:
      - sudo apt update
      - sudo apt install software-properties-common
      - sudo add-apt-repository ppa:deadsnakes/ppa
      - sudo apt update
      - sudo apt install python3.7 -y
      - python -V
      - pip3 install checkov
      - cd /usr/bin
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - unzip -o terraform.zip

  build:
    commands:   
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -no-color
      - terraform plan -out tf.plan
      - terraform show -json tf.plan > tf.json 
      - checkov -f tf.json

  post_build:
    commands:
      - echo "Checkov test is completed on `date`"
