version: 0.2

env:
  variables:
    TF_VERSION: "1.0.6"

phases:

  install:
    commands:
      - cd /usr/bin
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - unzip -o terraform.zip

  build:
    commands:   
      - cd "$CODEBUILD_SRC_DIR"
      - cd test/
      - go mod init "tftest"
      - go test -v

  post_build:
    commands:
      - echo "terratest completed on `date`"
