version: 0.2

env:
  variables:
    TF_VERSION: "1.0.6"

phases:

  install:
    runtime-versions:
      python: latest
    commands:
      - cd /usr/bin
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - unzip -o terraform.zip
      - 'curl -L "$(curl -s https://api.github.com/repos/accurics/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz'
      - tar -xf terrascan.tar.gz terrascan
      - chmod +x terrascan

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - terrascan scan

  post_build:
    commands:
      - echo "Terrascan test is completed on `date`"
